services:
  backend:
    build: ./backend
    container_name: locadora-backend
    ports:
      - "8085:8085"
    networks:
      - locadora-net

  frontend:
    build: ./frontend
    container_name: locadora-frontend
    ports:
      - "5173:5173"
    networks:
      - locadora-net
    depends_on:
      - backend

networks:
  locadora-net: